#!/bin/bash

black() { echo -e "$(tput setaf 0)$*$(tput sgr0)"; }
red() { echo -e "$(tput setaf 1)$*$(tput sgr0)"; }
green() { echo -e "$(tput setaf 2)$*$(tput sgr0)"; }
yellow() { echo -e "$(tput setaf 3)$*$(tput sgr0)"; }
blue() { echo -e "$(tput setaf 4)$*$(tput sgr0)"; }
magenta() { echo -e "$(tput setaf 5)$*$(tput sgr0)"; }
cyan() { echo -e "$(tput setaf 6)$*$(tput sgr0)"; }
white() { echo -e "$(tput setaf 7)$*$(tput sgr0)"; }

# set -e # fail on error

BASENAME=$(basename `pwd`)

if [ ! -f "`pwd`/bin/magento" ]; then
  red "You're not in the magento directory"
  exit 1
fi

green "Setting configuration options..."
CONFIG_OPTIONS=(
    general/locale/timezone='America/Chicago'
    web/cookie/cookie_lifetime=31536000
    admin/security/session_lifetime=3153600
    dev/debug/debug_logging=1
)

HAS_ELASTICSEARCH="$(php bin/magento module:status 'Magento_Elasticsearch' | grep -qv 'Module is enabled'; echo $?)"
if [ 1 == $HAS_ELASTICSEARCH ]; then
    CONFIG_OPTIONS+=(
        catalog/search/elasticsearch_server_hostname='127.0.0.1'
        catalog/search/elasticsearch_index_prefix=$BASENAME
    )
fi

for key in "${!CONFIG_OPTIONS[@]}"; do
    OPTION="$(echo ${CONFIG_OPTIONS[$key]} | cut -d'=' -f1)"
    VALUE="$(echo ${CONFIG_OPTIONS[$key]} | cut -d'=' -f2-)"
    
    yellow "Setting option: ${OPTION} = ${VALUE}"
    php bin/magento config:set "${OPTION}" "${VALUE}"
done

cyan "Done"

green "\nSetting developer mode..."
php bin/magento deploy:mode:set developer

green "\nRunning reindexation..."
php bin/magento indexer:reindex

green "\nDisabling caches..."
php bin/magento cache:disable full_page

green "\n"'Switching to "developer" mode...'
php bin/magento deploy:mode:set developer

green "\nCleaning caches..."
php bin/magento cache:clean full_page config

if [ -d "`pwd`/.idea" ]; then
    green "\nGenerating URN mappings..."
    php bin/magento dev:urn-catalog:generate --ide=phpstorm .idea/misc.xml
    cyan "Done"
fi
