#!/bin/bash

DB_NAME="$(m2-db-name)"

if ! (echo $* | grep --quiet -E '(\s+|^)--no-ask(\s+|$)'); then
  read -p "Drop database ${DB_NAME}. Are you sure (y/n)? " choice
  case "$choice" in 
    y|Y ) ;;
    n|N ) exit 1;;
    * ) echo "invalid input"; exit 1;;
  esac
  echo -e "\n"
fi

echo "drop database if exists \`${DB_NAME}\`;" | mysql
