#!/bin/bash

if [ ! -f "`pwd`/bin/magento" ]; then
  red "You're not in the magento directory"
  exit 1
fi

DB_NAME="$(m2-db-name)"
URL=$1

if [ "${URL}" == "" ]; then
  URL="https://$(m2-db-name).test/"
fi

if ! (echo $* | grep --quiet -E '(\s+|^)--no-ask(\s+|$)'); then
  read -p "Update website URL to ${URL}'. Are you sure (y/n)? " choice
  case "$choice" in 
    y|Y ) ;;
    n|N ) exit 1;;
    * ) echo "invalid input"; exit 1;;
  esac
  echo -e "\n"
fi

php bin/magento app:config:import
php bin/magento config:set "web/secure/base_url" "${URL}"
php bin/magento config:set "web/unsecure/base_url" "${URL}"
